version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test_pw
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - "3305:3306"
    networks:
      - db_network
    restart: always
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6378:6379"
    networks:
      - db_network
    restart: always
  spring-boot:
    container_name: duaily-server
    build: .
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - db_network

networks:
  db_network:
    driver: bridge