version: '3'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6378:6379"
    networks:
      - db_network
    restart: always
  spring-boot:
    container_name: duaily-server
    image: leb0205/duaily_backend
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - db_network

networks:
  db_network:
    driver: bridge