spring:
  datasource:
    url: jdbc:mysql://localhost:3305/test_db?useSSL=false&serverTimezone=Asia/Seoul
    username: test
    password: test_pw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6378
  profiles:
    include:
      secret
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR