spring:
  ## RDB 설정
  datasource:
    url: jdbc:mysql://localhost:3305/test_db?useSSL=false&serverTimezone=Asia/Seoul
    username: test
    password: test_pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## Multi-part 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ## JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  ## jwt 설정
  jwt:
    secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWw
    access-token: 3600000
    refresh-token: 604800000
  ## Redis 설정
  redis:
    host: localhost
    port: 6378
## AWS 설정
cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET_NAME}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR