name: Release Drafter

on: 
  pull_request:
    branches:
      - main
    types:
      - opened
 
permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs_on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      
